### PR TITLE
Added twitter bootstrap (sass) still need to add custom theme

### PR DESCRIPTION
**Pull request by brentm5**
Was unsure of a theme to use on top of bootstrap need some input here

### CODE REVIEW

**Comment by brentm5** [comment]
I was unsure if i needed to add any tests to this... I didnt think assets needed tests but i manually made sure they loaded.

(I know you always forget these)
Here are some sites for themes:

http://www.lavishbootstrap.com/

http://bootswatch.com/

http://bootswatchr.com/edit/cad1a959

**Comment by drapergeek** [comment]
I'm not in the habit of testing layouts personally.  There are some that do but I think its unnecessary.

As for a theme, I say lets just go with the stock theme right now, if we ever care more about looks we'll get a designer to take care of that.

This does need a basic layout with flashes and such.   I'm sure you can find them a lot of places around the web to just copy and paste for rails.

**Comment by brentm5** [comment]
I added a basic fluid layout with the following elements

fluid container with:
Navbar, 
8 column centered flash row
12 column main content row

**Comment by brentm5** [comment]
its going to fail... need to get in the habit of rake before i change anything

**Comment by drapergeek** [comment]
Have you checked an actual page to see how it looks?  It so take a screenshot and attach it to the P.  This is a good practice to follow anytime you're working on things that are visual changes primarily.

**Comment by brentm5** [comment]
IMg1

Found a way to do it, dropbox is a piece of shit and you cant just link to the direct url easily so i had to use a link

**Comment by drapergeek** [comment]
Very nice, and now show the home page w/ some content please.

**Comment by brentm5** [comment]
sorry... we do not have any content maybe if someone added more features

**Comment by brentm5** [comment]
AnotherLink

**Comment by brentm5** [comment]
Btw i did not add a sidebar or anything for the left hand side it was simply just to put some sort of theme on the app.

**Comment by drapergeek** [comment]
Yea i don't see any point in a sidebar currently.

**Comment by drapergeek** [comment]
This is good to merge once squashed.

**Pull request merged**
